In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
df = pd.read_csv("/content/drive/MyDrive/diabetes.csv")

In [4]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc

In [7]:
df = df.dropna() # drop rows with nan values

In [8]:
Xs = df.drop(columns='Diabetes_012') #independent variable array
ys = df['Diabetes_012']


X_train, X_test, y_train, y_test = train_test_split(
    Xs, ys, test_size=0.2, random_state=42)

In [9]:
# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [11]:
# Evaluate the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))


# evaluate the model
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 84.83%
Confusion Matrix:
 [[41755     0  1040]
 [  871     0    73]
 [ 5714     0  1283]]


In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor()

In [13]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [19]:
y_rpred = rf.predict(X_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
y_rpred

array([0., 0., 0., ..., 0., 0., 0.])

In [18]:
y_test

219620    0.0
132821    0.0
151862    0.0
139717    0.0
239235    0.0
         ... 
169513    2.0
182415    0.0
109739    0.0
181671    0.0
202118    0.0
Name: Diabetes_012, Length: 50736, dtype: float64

In [31]:
# Assuming 'rf' is your RandomForestClassifier
y_pred_proba = rf.predict_proba(X_test)  # Get predicted probabilities for Logistic Regressor

name='Random Forest'
accuracy = accuracy_score(y_test, y_rpred)
precision = precision_score(y_test, y_rpred, average='macro')
recall = recall_score(y_test, y_rpred, average='macro')
f1 = f1_score(y_test, y_rpred, average='macro')
roc_auc = roc_auc_score(y_test, y_rpred_proba, multi_class='ovr') # Use predicted probabilities

# Print results
print(f'Classifier: {name}')
print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')
print(f'ROC AUC Score: {roc_auc:.4f}')
print('\n')

name='Logistic Regressor'
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
roc_auc = roc_auc_score(y_test, y_pred_proba, multi_class='ovr') # Use predicted probabilities for Logistic Regressor

 # Print results
print(f'Classifier: {name}')
print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')
print(f'ROC AUC Score: {roc_auc:.4f}')
print('\n')

Classifier: Random Forest
Accuracy: 0.8417
Precision: 0.4464
Recall: 0.3888
F1 Score: 0.3983
ROC AUC Score: 0.7416


Classifier: Logistic Regressor
Accuracy: 0.8483
Precision: 0.4664
Recall: 0.3864
F1 Score: 0.3965
ROC AUC Score: 0.7416




/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
